M48
; DRILL file {KiCad 9.0.7} date 2026-02-28T16:38:33+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-28T16:38:33+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X76.6Y-103.25
X89.28Y-38.52
T2
X78.1Y-40.1
X78.1Y-150.05
X119.4Y-40.1
X119.4Y-150.05
M30
